baseURL = "https://DotGab.github.io/Blog/"
languageCode = "en-us"
title = "DotGab"
theme = "m10c"

[params]
  author = "DotGab"
  description = "A place to share things"
  avatar = "static/avatar.jpg"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/DotGab"
